# Generated by Django 2.2.11 on 2020-04-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
