# Generated by Django 2.2.11 on 2020-04-10 17:40

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.PositiveIntegerField(validators=[users.models.validate_zip])),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default='B', max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(default=users.models.Profile, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
