# Generated by Django 2.2.11 on 2020-04-10 19:37

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.IntegerField(validators=[users.models.validate_zip]),
        ),
    ]
