# Generated by Django 2.2.11 on 2020-04-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200411_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default',
        ),
    ]
